---
version: "3.7"
services:
  lidarr-extended:
    image: randomninjaatk/lidarr-extended:latest
    container_name: lidarr-extended
    volumes:
      - /home/lidarr/config:/config
      - /home/lidarr/downloads:/downloads-lidarr-extended
      - /home/lidarr/rootmusic:/music
    environment:
      - TZ=Europe/London
      - PUID=0
      - PGID=0
      - enableAudioScript=true
      - enableVideoScript=false
      - scriptInterval=15m
      - configureLidarrWithOptimalSettings=true
      - searchSort=date
      - audioFormat=flac
      - audioBitrate=lossless
      - requireQuality=true
      - enableReplaygainTags=true
      - audioLyricType=both
      - dlClientSource=both
      - arlToken=65ef2246e944c5ce83262971751869c9fccf0e19931e4cf169ba2dacca734bcaf1191f6a655d90b9822f6165e3ba60823d7e48e7f9c00d6801c7097618775890ec068efbdc4dc9df154c9fd90af00cda494d00ad120915707cce5dcbfd97ff19
      - tidalCountryCode=GB
      - addDeezerTopArtists=false
      - addDeezerTopAlbumArtists=false
      - addDeezerTopTrackArtists=false
      - topLimit=10
      - addRelatedArtists=false
      - numberOfRelatedArtistsToAddPerArtist=5
      - lidarrSearchForMissing=true
      - addFeaturedVideoArtists=false
      - plexUrl=http://10.159.1.168:32400
      # - plexToken=Token_Goes_Here
      - youtubeSubtitleLanguage=en
      - enableQueueCleaner=true
      - matchDistance=5
      - enableBeetsTagging=true
      - beetsMatchPercentage=90
      - retryNotFound=90
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      lidarr-net:
        ipv4_address: 172.20.128.2

networks:
  lidarr-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.128.0/24
