#!/bin/bash

# To be run after installation of oh-my-zsh

# install oh-my-zsh plugins
cd ~/.oh-my-zsh/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

rm -rf ~/.zshrc # remove the default .zshrc generated by the oh-my-zsh install

ln -s ~/.dotfiles/.zshrc ~/.zshrc
ln -s ~/.dotfiles/.bash_aliases ~/.zsh_aliases
ln -s ~/.dotfiles/.bash_aliases ~/.bash_aliases
ln -s ~/.dotfiles/.vim ~/.vim
ln -s ~/.dotfiles/bin ~/bin
ln -s ~/.dotfiles/.vimrc ~/.vimrc
ln -s ~/.dotfiles/.bash_profile ~/.bash_profile
ln -s ~/.dotfiles/.bash_profile_remote ~/.bash_profile_remote
mkdir -p ~/bin/
ln -s ~/.dotfiles/deploy-remote-home.sh ~/bin/deploy-remote-home.sh

# install vim plugins latest version

rm -rf ~/.dotfiles/.vim/bundle/*
cd ~/.dotfiles/.vim/bundle/
git clone git@github.com:/altercation/vim-colors-solarized.git
git clone git@github.com:/vim-scripts/Conque-Shell.git
git clone git@github.com:/ryanoasis/vim-devicons.git
git clone git@github.com:/tpope/vim-rails.git
git clone git@github.com:/tpope/vim-bundler.git
git clone git@github.com:/vim-airline/vim-airline
git clone git@github.com:/scrooloose/nerdtree.git
git clone git@github.com:vim-syntastic/syntastic.git
git clone git@github.com:jelera/vim-javascript-syntax.git
git clone git@github.com:/godlygeek/tabular.git

# install oh-my-zsh plugins
cd ~/.oh-my-zsh/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git


# install font for vim-fonts
git clone https://github.com/powerline/fonts.git
cd fonts
./install.sh
cd ..
rm -rf fonts

./configure-osx.sh

echo ""
echo ""
echo " -!-!-!- "
echo "STOP - If using iterm2, set your font in iterm2 settings to a Powerline font both for ASCII and non-ASCII font types!"
echo " -!-!-!- "
echo "ONCE DONE - open new terminal and you're complete"
echo ""
echo ""


