[window]
startup_mode = "Maximized"
title = "Ubuntu Linux"
dynamic_title = true

[scrolling]
history = 100_000

[font]
size = 18

  [font.normal]
  family = "DroidSansMono Nerd Font"

[cursor.style]
shape = "Underline"
blinking = "On"

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" },
]

[selection]
save_to_clipboard = true
