#!/bin/bash

export VIMZ_USER="__VIMZ_USERNAME__"
export VIMZ_EMAIL="__VIMZ_GITHUB_EMAIL__"
export VIMZ_JOPLIN_SYNC_PASSWORD="__VIMZ_JOPLIN_SYNC_PASSWORD__"
export VIMZ_OPENAPI_ACCESS_TOKEN="__VIMZ_OPENAPI_ACCESS_TOKEN__"

